//HintName: MyClass.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the MyGenerator source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace MyNamespace;
public class MyClass
{
    public MyClass(string firstName, string lastName)
    {
        FirstName = firstName;
        LastName = lastName;
        FullName = string.Concat(FirstName, " ", LastName);
    }

    public string FirstName { get; }

    public string LastName { get; }

    /// <summary>
    /// Gets the full name.
    /// </summary>
    public string FullName { get; }
}
